# control
wandb_mode : "online"

# Hyperparameters
learning_rate: 1e-4
epochs: 1
weight_decay : 0.01
batch_size : 16
sequence_length : 512
model_name : "meta-llama/Llama-2-7b-hf"
repetition_penalty : 1.25

# dataset
train_size: 20000
val_size: 175
use_prompt: True

# Quantization (necessary for Llama2)
load_in_4bit: True
