# control
wandb_mode : "online"

# Hyperparameters
learning_rate: 1e-4
epochs: 2
weight_decay : 0.01
batch_size : 8
sequence_length : 512
model_name : "distilgpt2"

# dataset
train_size: 16
val_size: 4
use_prompt: True

# Quantization (necessary for Llama2)
load_in_4bit: False