# control
wandb_mode : "online"

# Hyperparameters
learning_rate: 1e-4
epochs: 2
weight_decay : 0.01
batch_size : 24
sequence_length : 512
model_name : "meta-llama/Llama-2-7b-hf"

# dataset
train_size: 40000
val_size: 3200
use_prompt: True

# Quantization (necessary for Llama2)
load_in_4bit: True