# control
wandb_mode : "online"
save_model_at_end : True
train_summ : True
train_with_nli : True
train_nli : False
eval_summ : False

# Hyperparameters
learning_rate: 1e-3
epochs: 2
weight_decay : 0.01
batch_size : 4
eval_batch_size : 4
sequence_length : 512
model_name : "ernlavr/adv_nlp2023/model_glwgz9uz:v0"
repetition_penalty : 1.25
eval_steps : 25  # processing steps before evaluation takes place


# evaluation
wandb_num_examples : 10  # number of examples to save in W&B table

# dataset
train_size: 32
val_size: 5000
use_prompt: True

# Quantization (necessary for Llama2)
load_in_4bit: True
