# control
wandb_mode : "offline"
save_model_at_end : True
train_summ : False
train_nli : True

# Hyperparameters
learning_rate: 1e-4
epochs: 2
weight_decay : 0.01
batch_size : 32
eval_batch_size : 32
sequence_length : 512
model_name : "distilbert-base-uncased"
repetition_penalty : 1.25
eval_steps : 50  # processing steps before evaluation takes place

# evaluation
num_examples : 10  # number of examples to save in W&B table

# dataset
train_size: 50000
val_size: 5000
use_prompt: True

# Quantization (necessary for Llama2)
load_in_4bit: True
