# Config for running WANDB param-sweeps
# Reference: https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
# Create a sweep agent: `wandb sweep --project adv_nlp2023 conf/config.yaml`

program: main.py
method: grid # grid, bayes, random
parameters:
  use_prompt:
    values:
      - True
      - False
  train_size:
    values: 
      - 40000
  val_size:
    values:
      - 4000
  epochs:
    values:
      - 2
metric:
  name: validation_loss # https://docs.wandb.ai/guides/sweeps/define-sweep-configuration
  goal: minimize